services:
  app:
    build:
      context: https://github.com/yourusername/your-repository.git#main
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - OAUTH_SERVICE_URL=${OAUTH_SERVICE_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - GOTO_ACCOUNT_KEY=${GOTO_ACCOUNT_KEY}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    build:
      context: https://github.com/yourusername/your-repository.git#main
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nginx-logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  nginx-logs: